config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  resources :users, only: [:index, :show] do
    resources :follows, only: [:show, :create]
    resources :unfollows, only: [:show, :create]
    member do
      get :following, :followers
    end
  end

  get 'search' => 'users#search'

  resources :posts do
    resources :reviews, only: [:index, :create]
    resource :like, only: [:show, :create, :destroy]
  end

  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resource :profile, only: [:show, :edit, :update]

  resources :tags do
    get 'posts', to: 'posts#tags'
  end

  get 'goods/search'

  resources :rooms, only: [:index, :show, :create]
  resources :messages, only: [:create, :edit, :update, :destroy]
  resources :notifications, only: [:index, :destroy]
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id            :bigint           not null, primary key
#  introduction  :text(65535)
#  nickname      :string(191)
#  sportingevent :string(191)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
    belongs_to :user
    has_one_attached :avatar
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!

    def show
        @profile = current_user.profile
    end

    def edit
        @profile = current_user.prepare_profile
    end

    def update
        @profile = current_user.prepare_profile
        @profile.assign_attributes(profile_params)
        if @profile.save
            redirect_to profile_path, notice: 'プロフィールを更新しました'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit
        end
    end

    private
    def profile_params
        params.require(:profile).permit(:nickname, :introduction, :avatar, :sportingevent)
    end
end

app/views/profiles/edit.html.haml
.container
  .profile-card-body.text-center
    %h5.card-title.pt-3.mb-4 プロフィール
    = image_tag current_user.avatar_image, class: 'profile-image mb-3'
    = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
      %div
        = f.label :avatar, class: 'avatar-btn' do
          %p 画像を変更
          = f.file_field :avatar, class: 'avatar-field', style: 'display:none'  
      %div
        = f.label :nickname, '名前', class: 'nickname-text mb-1'
      %div
        = f.text_field :nickname, class: 'nickname-field mb-4' 
      %div
        = f.label :競技種目, class: 'sportingevent-name mb-1'
      %div.mb-3
        = f.select :sportingevent, [["野球", "野球"], ["ソフトボール", "ソフトボール"], ["サッカー", "サッカー"],["フットサル", "フットサル"], ["ゴルフ", "ゴルフ"], ["バスケットボール", "バスケットボール"], ["ラグビー", "ラグビー"], ["テニス", "テニス"], ["バレーボール", "バレーボール"], ["陸上", "陸上"], ["水泳", "水泳"], ["ボクシング", "ボクシング",], ["キックボクシング", "キックボクシング"], ["総合格闘技", "総合格闘技"], ["アメフト", "アメフト"], ["ボディービルダー", "ボディービルダー"], ["その他", "その他"]], include_blank: true, class: 'select-field mb-3'
      %div 
        = f.label :introduction, '自己紹介', class: 'introduction-text mb-2'
      %div
        = f.text_area :introduction, class: 'introduction-field mb-5'
      .actions
        = f.submit "保存", class: 'login-btn'

  = render 'commons/newpostbtns'

= render 'commons/footer'
          

app/views/profiles/show.html.haml
.container
  .profile-card-body.text-center
    %h5.card-title.pt-3.mb-4.fw-bold プロフィール
    = image_tag current_user.avatar_image , class: 'profile-image mb-3'
    %p.fs-4.mb-4.fw-bold= current_user.display_name
    
    .profilePage_user_have
      .profilePage_user_have_item
        = link_to followers_user_path(current_user.id) do
          #follower
            フォロワー
            %span#follower-count= current_user.followers.count
            人
      .profile-vertical-line 
      .profilePage_user_have_item
        = link_to following_user_path(current_user.id) do
          #follow
            フォロー
            %span#following-count= current_user.followings.count
            人
    .profile-sportingevent 
      %p.sportingevent-title.mb-2 競技種目
      %p= current_user.profile&.sportingevent
    .profile-introduction.mb-5
      %p.introduction.mb-3 自己紹介
      %p.introduction-content= current_user.profile&.introduction
        

    = link_to 'プロフィールを編集する', edit_profile_path, method: :get, class: 'login-btn3'

  = render 'commons/newpostbtns'

= render 'commons/footer'
    
        
      

      
        
        