config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  resources :users, only: [:index, :show] do
    resources :follows, only: [:show, :create]
    resources :unfollows, only: [:show, :create]
    member do
      get :following, :followers
    end
  end

  get 'search' => 'users#search'

  resources :posts do
    resources :reviews, only: [:index, :create]
    resource :like, only: [:show, :create, :destroy]
  end

  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resource :profile, only: [:show, :edit, :update]

  resources :tags do
    get 'posts', to: 'posts#tags'
  end

  get 'goods/search'

  resources :rooms, only: [:index, :show, :create]
  resources :messages, only: [:create, :edit, :update, :destroy]
  resources :notifications, only: [:index, :destroy]
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :bigint           not null, primary key
#  action     :string(191)      default(""), not null
#  checked    :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  message_id :integer
#  post_id    :integer
#  review_id  :integer
#  room_id    :integer
#  visited_id :integer          not null
#  visitor_id :integer          not null
#
# Indexes
#
#  index_notifications_on_post_id     (post_id)
#  index_notifications_on_review_id   (review_id)
#  index_notifications_on_visited_id  (visited_id)
#  index_notifications_on_visitor_id  (visitor_id)
#
class Notification < ApplicationRecord
    default_scope -> { order(created_at: :desc) }
    belongs_to :post, optional: true
    belongs_to :review, optional: true
    belongs_to :room, optional: true
    belongs_to :message, optional: true
    belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
    belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
    before_action :authenticate_user!

    def index
        @notifications = current_user.passive_notifications.includes([:post, :visitor, :visited])
    end

    def destroy
        @notifications = current_user.passive_notifications.destroy_all
        redirect_to notifications_path
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_circle.html.haml
-# - if unchecked_notifications.any?
-#   %span.fa-stack
-#     %i.fa.fa-circle
      

app/views/notifications/_notification.html.haml
- visitor = notification.visitor
- visited = notification.visited
.notification-list
  .form-inline 
    %span
      = link_to user_path(visitor) do
        = image_tag visitor.avatar_image, class: 'notification-avatar'
        %strong.mb-4
          = visitor.username
      さんが

      - case notification.action 
      - when 'follow' then 
        %span あなたをフォローしました。
      - when 'like' then 
        = link_to 'あなたの投稿', notification.post, style: "fw-bold"
        %span にいいねしました。
      - when 'review' then 
        - if notification.post.user_id == visited.id
          = link_to 'あなたの投稿にレビュー', notification.post, style: 'fw-bold'
        -else
          %span
            = link_to post_path(notification.post) do
              = image_tag notification.post.user.avatar_image, class: 'notification-avatar'
              %strong
                = notification.post.username + 'さんの投稿にレビュー'
        = 'しました。'
        %p.text-muted.mb-0
          -# = Review.find_by(id: notification.review_id)&.review
      - when 'message' then
        %span あなたにメッセージを送信しました。
  .message-time.small.text-muted
    = time_ago_in_words(notification.created_at).upcase
  %hr

app/views/notifications/index.html.haml
.container 
  .notification-card.mt-5
    %h2.notification.text-center 通知
    .notification-destroy-btn
      = link_to notification_path(@notifications), data: { confirm: "【確認】メッセージをすべて削除してもよろしいですか？" }, method: :delete do
        %i.fa.fa-trash-o.message-destroy-btn.mb-3.fw-bold
          すべて削除
    -if @notifications.exists?
      = render @notifications
    - else
      %p.text-center 通知はありません
  
  = render 'commons/newpostbtns'

= render 'commons/footer'

          