config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  resources :users, only: [:index, :show] do
    resources :follows, only: [:show, :create]
    resources :unfollows, only: [:show, :create]
    member do
      get :following, :followers
    end
  end

  get 'search' => 'users#search'

  resources :posts do
    resources :reviews, only: [:index, :create]
    resource :like, only: [:show, :create, :destroy]
  end

  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resource :profile, only: [:show, :edit, :update]

  resources :tags do
    get 'posts', to: 'posts#tags'
  end

  get 'goods/search'

  resources :rooms, only: [:index, :show, :create]
  resources :messages, only: [:create, :edit, :update, :destroy]
  resources :notifications, only: [:index, :destroy]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string(191)      default(""), not null
#  encrypted_password     :string(191)      default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(191)
#  username               :string(191)      default(""), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, through: :following_relationships, source: :following
  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower
  has_many :messages
  has_many :entries
  has_many :rooms, through: :entries
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, length: { maximum: 15 }
  validates :password, presence: true, length: { minimum: 6 }
  # validates :password_confirmation, presence: true, length: { minimum: 6 }

  def display_name
    profile&.nickname || self.username
  end

  def has_written?(post)
    posts.exists?(id: post.id)
  end

  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'icon_default.png'
    end
  end

  def post_image
    if post&.image&.attached?
      post.image
    else
      'noimage.png'
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.username = 'guest'
    end
  end

  def self.search(keyword)
    where(['username like?', "%#{keyword}%"])
  end

  def follow!(user)
    user_id = get_user_id(user)
    following_relationships.create!(following_id: user_id)
  end

  def unfollow!(user)
    user_id = get_user_id(user)
    relation = following_relationships.find_by!(following_id: user_id)
    relation.destroy!
  end

  def has_followed?(user)
    following_relationships.exists?(following_id: user.id)
  end

  def follower_counts(user)
    user.followers.count
  end

  def following_counts(user)
    user.followings.count
  end

  def has_liked?(post)
    likes.exists?(post_id: post.id)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  private
  def get_user_id(user)
    if user.is_a?(User)
      user.id
    else
      user
    end
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
    before_action :check_guest, only: :create

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_action :check_guest, only: %i[update destroy]

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    def new_guest
        user = User.guest
        sign_in user
        redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
        @users = User.includes(:profile).page(params[:page])
    end

    def show
        @user = User.find(params[:id])
        reviews = Review.where(user_id: current_user.id).pluck(:post_id)
        @reviews = Post.find(reviews)
        review_list = Review.where(user_id: @user.id).pluck(:post_id)
        @review_list = Post.find(review_list)
        if user_signed_in?
            @currentUserEntry = Entry.where(user_id: current_user.id)
            @userEntry = Entry.where(user_id: @user.id)
            unless @user.id == current_user.id
                @currentUserEntry.each do |cu|
                    @userEntry.each do |u|
                        if cu.room_id == u.room_id
                            @haveRoom = true
                            @roomId = cu.room_id
                        end
                    end
                end
                unless @haveRoom
                    @room = Room.new
                    @entry = Entry.new
                end
            end
        end
    end

    def search
        @users = User.search(params[:keyword])
        @users = @users.page(params[:page]).per(12)
        @keyword = params[:keyword]
        render 'index'
    end

    def followers
        @user = User.find(params[:id])
        @users = @user.followers.page(params[:page])
    end

    def following
        @user = User.find(params[:id])
        @users = @user.followings.page(params[:page])
    end
end

app/views/users/_contact.html.haml
- if user_signed_in?
  - unless @user.id == current_user.id
    - if @haveRoom == true
      = link_to "DMする", room_path(@roomId), class: 'message-button fw-bold'
    - else
      = form_with(model:@room, local: true) do |f|
        = fields_for @entry do |e|
          = e.hidden_field :user_id, value: @user.id
          = f.submit "DMする", class: 'message-button fw-bold'

app/views/users/followers.html.haml
.container 
  .userlist-card.mb-3 
    %h4.followers-title.text-center.fw-bold.mb-5 フォロワー
    .users-list
    - @users.each do |user|
      %ul
        = link_to user_path(user), class: 'no-underline' do
          %li.users-list-item
            .users-list-image
              %p= image_tag user.avatar_image, class: 'userlist-avatar'
            .users-list-info
              %p= user.username
              - if user.profile&.sportingevent.present?
                %p.users-sporting-event= "競技種目: #{user.profile.sportingevent}"

  = render 'commons/newpostbtns'
        
= render 'commons/footer'

app/views/users/following.html.haml
.container 
  .userlist-card.mb-3 
    %h4.followers-title.text-center.fw-bold.mb-5 フォロー中
    .users-list
    - @users.each do |user|
      %ul
        = link_to user_path(user), class: 'no-underline' do
          %li.users-list-item
            .users-list-image
              %p= image_tag user.avatar_image, class: 'userlist-avatar'
            .users-list-info
              %p= user.username
              - if user.profile&.sportingevent.present?
                %p.users-sporting-event= "競技種目: #{user.profile&.sportingevent}"

  = render 'commons/newpostbtns'
        
= render 'commons/footer'

app/views/users/index.html.haml
.container 
  .userlist-card.mt-5
    %h4.user-list-name.text-center.fw-bold.mb-4 ユーザー一覧
    .search-form.text-center.mb-5
      = form_with url: search_path, method: :get, remote: true do |f|
        = f.text_field :keyword, value: @keyword, placeholder: '(例) ユーザーネーム',  class: 'search-field'
        = f.submit "検索", class: 'search-btn'
    
      - if @users.present?
      - else
        %p.text-center.mt-5 該当するユーザーはいません

    .users-list
      - @users.each do |user|
        %ul
        = link_to user_path(user), class: 'no-underline' do
          %li.users-list-item
            %p= image_tag user.avatar_image, class: 'userlist-avatar'
            %p= user.username

    = paginate @users

  = render 'commons/newpostbtns'

= render 'commons/footer'
          

app/views/users/show.html.haml
.container#user-show{ data: { user_id: @user.id, following_id: current_user.id}}
  .profile-card-body.text-center
    %h5.card-title.pt-3.mb-4 プロフィール
    = image_tag @user.avatar_image , class: 'profile-image mb-3'
    %p.fs-4.mb-4.fw-bold= @user.display_name
    
    .profilePage_user_have
      .profilePage_user_have_item
        = link_to followers_user_path(@user.id) do
          #follower
            フォロワー
            %span#follower-count= @user.followers.count
            人
      .profile-vertical-line 
      .profilePage_user_have_item
        = link_to following_user_path(@user.id) do
          #follow
            フォロー
            %span#following-count= @user.followings.count
            人
    - if @user != current_user
      .profilePage_user_have_item.mb-3
        .follow-btn.hidden.fw-bold.text-center
          %p フォローする
        .unfollow-btn.hidden.fw-bold.text-center
          %p フォローを外す
      .dm-btn.mb-4  
        = render "contact"

    .profile-sporting-event
      %p.introduction.mb-2 競技種目 
      %p.introduction-content= @user.profile&.sportingevent
        

    .profile-introduction.mb-4 
      %p.introduction.mb-3 自己紹介
      %p.introduction-content= @user.profile&.introduction
        
  = render 'commons/tabs'

  = render 'commons/newpostbtns'

= render 'commons/footer'
    
= javascript_pack_tag 'relation.js'
= javascript_pack_tag 'users.js'
    
        
      

      
        
        