config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  resources :users, only: [:index, :show] do
    resources :follows, only: [:show, :create]
    resources :unfollows, only: [:show, :create]
    member do
      get :following, :followers
    end
  end

  get 'search' => 'users#search'

  resources :posts do
    resources :reviews, only: [:index, :create]
    resource :like, only: [:show, :create, :destroy]
  end

  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resource :profile, only: [:show, :edit, :update]

  resources :tags do
    get 'posts', to: 'posts#tags'
  end

  get 'goods/search'

  resources :rooms, only: [:index, :show, :create]
  resources :messages, only: [:create, :edit, :update, :destroy]
  resources :notifications, only: [:index, :destroy]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  content    :text(65535)      not null
#  name       :string(191)      not null
#  price      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
class Post < ApplicationRecord
    has_one_attached :image
    has_one_attached :avatar
    belongs_to :user
    has_many :reviews, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :tag_relationships, dependent: :destroy
    has_many :tags, through: :tag_relationships
    has_many :notifications, dependent: :destroy

    validates :name, presence: true, length: { maximum: 30 }
    validates :content, presence: true, length: { maximum: 300 }
    validates :price, presence: true

    def avg_score
        unless self.reviews.empty?
          reviews.average(:score).round(1).to_f
        else
          0.0
        end
      end

      def review_score_percentage
        unless self.reviews.empty?
          reviews.average(:score).round(1).to_f*100/5
        else
          0.0
        end
    end

    def like_by(user)
        likes.where(likes: { user_id: user }).last
    end

    def liked_by?(user)
        like_by(user).present?
    end

    def save_tags(savepost_tags)
        current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
        old_tags = current_tags - savepost_tags
        new_tags = savepost_tags - current_tags
        old_tags.each do |old|
            self.tags.delete Tag.find_by(tag_name: old)
        end
        new_tags.each do |new|
            new_post_tag = Tag.find_or_create_by(tag_name: new)
            self.tags << new_post_tag
        end
    end

    def like_counts(post)
       likes.count
    end

    def self.create_all_ranks
      Post.find(Like.group(:post_id).order('count(post_id) desc').limit(4).pluck(:post_id))
    end

    def self.create_review_ranks
      Post.find(Review.group(:post_id).order('avg(score) desc').limit(4).pluck(:post_id))
    end

    def create_notification_review!(current_user, review_id)
      temp_ids = Review.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
      temp_ids.each do |temp_id|
        save_notification_review!(current_user, review_id, temp_id['user_id'])
      end
      save_notification_review!(current_user, review_id, user_id) if temp_ids.blank?
    end

    def save_notification_review!(current_user, review_id, visited_id)
      notification = current_user.active_notifications.new(
        post_id: id,
        review_id: review_id,
        visited_id: visited_id,
        action: 'review'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end

    def create_notification_like!(current_user)
      temp = Notification.where(['visitor_id = ? and visited_id = ? and post_id = ? and action = ? ', current_user.id, user_id, id, 'like'])
      if temp.blank?
        notification = current_user.active_notifications.new(
          post_id: id,
          visited_id: user_id,
          action: 'like'
        )
        if notification.visitor_id == notification.visited_id
          notification.checked = true
        end
        notification.save if notification.valid?
      end
    end

    def post_image
      if post&.image&.attached?
        post.image
      else
        'noimage.png'
      end
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only:[:new, :create, :edit, :destory]

    def index
        @posts = Post.includes(:user)
        @posts = @posts.page(params[:page]).per(8)
        @post_ranks = Post.create_all_ranks
        @tag_list = Tag.all
        @tag_ranks = Tag.find(TagRelationship.group(:tag_id).order(Arel.sql('count(tag_id)desc')).limit(20).pluck(:tag_id))
        @review_ranks = Post.create_review_ranks
    end

    def show
        @post = Post.find(params[:id])
        @review = Review.new
        @post_tags = @post.tags
    end

    def new
        @post = current_user.posts.build
    end

    def create
        @post = current_user.posts.build(post_params)
        tag_list = params[:post][:tag_name].split(nil)
        if @post.save!
          @post.save_tags(tag_list)
          redirect_to root_path, notice: '投稿が完了しました。'
        else
          render :new, notice: '投稿に失敗しました。'
        end
    end

    def edit
        @post = current_user.posts.find(params[:id])
    end

    def update
        @post = current_user.posts.find(params[:id])
        if @post.update(post_params)
            redirect_to post_path(@post)
        else
            render :new
        end
    end

    def destroy
        post = current_user.posts.find(params[:id])
        post.destroy!
        redirect_to root_path, notice: '削除に成功しました'
    end

    def tags
        @tag_list = Tag.all
        @tag = Tag.find(params[:tag_id])
        @posts = @tag.posts.all
        @posts = @posts.page(params[:page]).per(8)
    end

    private
    def post_params
        params.require(:post).permit(:name, :content, :price, :image).merge(user_id: current_user.id)
    end
end

app/views/posts/index.html.haml
%header
  = image_tag 'facebook_cover_photo_2.png', class: 'post-container-image'
.container 
  .post-container
    .post-card.mb-5 
      %h2.text-center.mt-3.mb-4.fw-bold Muscle nutriとは
      %p.post-discription.text-center 筋肉のためや健康維持のためにプロテインやサプリを利用する方が
      %p.post-discription.text-center.mb-5 プロテインやサプリの情報を共有し、自分とマッチするプロテインやサプリを選んでいただけるように作られたサービスです。
      %h2.text-center.mt-3.mb-4.fw-bold このサービスに込めた想い
      %p.post-discription.text-center 健康維持や筋トレ後の栄養補給、競技スポーツでのパフォーマンス向上をするために大事なのは栄養補給になります。
      %p.post-discription.text-center 現代の人々は栄養が偏りがちでバランスよく栄養を取れている人は多くはないはずです。
      %p.post-discription.text-center そして栄養補給の質を上げるためには食事とプラスでプロテインやサプリを補給することが良いとされています。
      %p.post-discription.text-center そこでプロテインやサプリ選びを失敗しないように口コミなどでプロテインやサプリの情報を共有し合い、
      %p.post-discription.text-center 自分に合ったプロテインやサプリを選んでいただけるように「Musclenutri」は誕生しました。
      %p.post-discription.text-center このサービスを使うことで、少しでも多くの人がバランスの良い栄養補給ができ、競技スポーツのパフォーマンス向上ができるように願っております。
  
  %h3.like-lank.text-center.fw-bold レビュー平均点数が高いプロテインやサプリ

  .post-card
    .row
      - @review_ranks.each.with_index(1) do |post, i|
        .col-sm-3.d-flex
          .card-body 
            = link_to post_path(post), class: 'post-link' do
              %p.post-title.text-center.no-underline.mb-3.fw-bold= "商品名: #{post.name}"
              - if post.image.attached? 
                = image_tag post.image, class: 'card-img-top'

  .post-card.text-center
    .row.mb-5
      .col-sm-6.d-flex
        .chart-card-body.text-center
          %h3.fw-bold ユーザーの競技種目別割合
          = pie_chart Profile.group(:sportingevent).count

      .col-sm-6
        .tag-card-body     
          .h3.post-tag-title.text-center.mb-5.fw-bold 人気のタグ
          .tag-list.text-center.no-underline.mb-5
            - @tag_ranks.each.with_index(1) do |list,i|
              .tag-count
                = link_to "##{list.tag_name}", tag_posts_path(tag_id: list.id), class: 'text-center tag-name mb-5'
                %span.tag-count-item= "#{list.posts.count}"

  %h2.text-center.mb-3.fw-bold 口コミされたプロテインとサプリ
  .post-card
    .row
      - @posts.each do |post|
        .col-sm-3.d-flex
          .post-card-body
            = link_to post_path(post), class: 'post-link' do
              %p.post-title.text-center.no-underline.mb-3.fw-bold= "商品名: #{post.name}"
              - if post.image.attached?
                = image_tag post.image, class: 'card-img-top'
              - else 
                = image_tag 'noimage.png', class: 'card-img-top'

              .post-avatar-name.text-center
                = image_tag post.user.avatar_image, class: 'avatar-image'
                .review-name
                  %p.text-left.no-underline= post.user.profile&.nickname
                  %p.post-sportingevent= "競技種目: #{post.user.profile&.sportingevent}"
    = paginate @posts
     
  = render 'commons/newpostbtns'
        
= render 'commons/footer'
          

    
    

app/views/posts/new.html.haml
.container
  .post-new-container.mt-5
    = form_with(model: @post, local: true) do |f|
      .review.text-center.mb-3 口コミ投稿
      %div.text-center.mb-4
        = f.label :name, '商品名', class: 'new-post-font'
      %div.text-center
        = f.text_field :name, class: 'product-name' 
      %div.text-center
        = image_tag 'noimage.png', class: 'product-noimage'
      %div 
        = f.label :image, class: 'avatar-btn' do
          %p.text-center 画像を選択
          = f.file_field :image, class: 'avatar-field', style: 'display:none' 
      %div.text-center.mb-3
        = f.label :price, '購入価格', class: 'new-post-font'
      %div.text-center.mb-5
        = f.number_field :price, step: '0.1', placeholder: '¥0', class: 'price-area'
      %div.text-center.mb-3
        %p.form-title #タグ（任意）※半角スペース区切りでタグ付けできます
      %div.text-center.mb-5
        = f.text_field :tag_name, placeholder: "タグをつけてください。複数つけるには','で区切ってください。", class: 'tag-area'
      %div.text-center.mb-3
        = f.label :content, '内容', class: 'new-post-font'
      %div.text-center.mb-5
        = f.text_area :content, placeholder: '(例) このプロテインはとても飲みやすくて粉も溶けやすいのでいいです！', class: 'content-area'
      %div.text-center
        = f.submit '投稿', class: 'newPost-login-btn'
        
= render 'commons/footer'
      

app/views/posts/show.html.haml
.container
  .post-card-body-show.mt-5#post-show{data: {post_id: @post.id}}
    %h5.post-title.text-center.no-underline.fw-bold.mb-4= "商品名: #{@post.name}"
    - if user_signed_in? && current_user.has_written?(@post)
      .delete-btn.mb-3
        = link_to post_path(@post.id), data: { confirm: "【確認】投稿を削除してもよろしいですか？" }, method: :delete do
          %i.fa.fa-trash-o.message-destroy-btn.mb-3.fw-bold
            削除する
    - if @post.image.attached?
      = image_tag @post.image, class: 'card-img-top mb-5'
    - else 
      = image_tag 'noimage.png', class: 'card-img-top mb-5'
    %p.product-price.text-center.no-underline= "購入価格: #{@post.price}円"
    %p.card-text.text-center.no-underline.mb-4= "感想: #{@post.content}"

    .tag-list.text-center.mb-3
      - @post_tags.each do |tag|
        .tag-count
          = link_to "##{tag.tag_name}", tag_posts_path(tag_id: tag.id)

    - if user_signed_in?
      .post-heart-btn
        .post-heart.active-heart.hidden{id: @post.id}
          = image_tag 'heart.svg', class: 'like-btn'
        .post-heart.inactive-heart.hidden{id: @post.id}
          = image_tag 'inactive-heart.svg', class: 'like-btn'
        .like-count 
          %p= @post.likes.count

    .post-avatar-name.text-center
      = link_to user_path(@post.user) do
        = image_tag @post.user.avatar_image, class: 'avatar-image mb-2'
      .review-name.mt-1.text-center.mb-2
        %p.text-left.no-underline= @post.user.profile&.nickname
    
    %p.text-center.mb-3 レビューを投稿

    .rating-box.mt-3.text-center
      = form_with(model: @review, url: post_reviews_path(@post), method: 'post', local: true) do |f|
        .main-rating.text-center
          .ratings
            %span.i.fa.fa-star-o#star
            %span.i.fa.fa-star-o#star
            %span.i.fa.fa-star-o#star
            %span.i.fa.fa-star-o#star
            %span.i.fa.fa-star-o#star
          
          .ml-3.rating-value-display.mb-3
            %span#rating-value-display> 0
            \/5 
        .review-hidden-field
          = f.hidden_field :post_id, value: @post.id
        .score-hidden-field
          = f.hidden_field :score, id: 'rating-value'
        .textarea-review
          = f.text_area :content, placeholder: '(例) 口コミ通りこのプロテインはとても味がよく飲みやすかったので、リピートします！'
        .review-button
          = f.submit 'レビューする', class: 'review-btn mt-3 mb-4'
        .review-show-button 
          = link_to 'レビュー閲覧', post_reviews_path(@post), class: "review-button2 btn btn-danger fw-bold", style: 'padding: 10px; border-radius: 30px;'
        
= render 'commons/newpostbtns'
        
= render 'commons/footer'

= javascript_pack_tag 'like.js'
= javascript_pack_tag 'review.js'

app/views/posts/tags.html.haml
.container 
  %h2.tag-title.text-center.mt-4
    = "##{@tag.tag_name}"
    のタグの投稿 #{"#{@posts.count}件"}

  .tag-post-card
    .row
      - @posts.each do |post|
        .col-sm-3.d-flex
          .post-card-body
            = link_to post_path(post), class: 'post-link' do
              - if post.image.attached?
                = image_tag post.image, class: 'card-img-top'
              %p.post-title.text-center.no-underline.mb-3= "商品名: #{post.name}"

              .post-avatar-name.text-center
                = image_tag post.user.avatar_image, class: 'avatar-image'
                .review-name
                  %p.text-left.no-underline= post.user.profile&.nickname
  = paginate @posts

  = render 'commons/newpostbtns'

= render 'commons/footer'
          